//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointerScan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PointerScan.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address (Hex):.
        /// </summary>
        internal static string AddressLabel_Label {
            get {
                return ResourceManager.GetString("AddressLabel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Size:.
        /// </summary>
        internal static string AddressSizeLabel_Label {
            get {
                return ResourceManager.GetString("AddressSizeLabel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Byte.
        /// </summary>
        internal static string AddressSizeOptions_1Byte {
            get {
                return ResourceManager.GetString("AddressSizeOptions_1Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Bytes.
        /// </summary>
        internal static string AddressSizeOptions_2Bytes {
            get {
                return ResourceManager.GetString("AddressSizeOptions_2Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Bytes.
        /// </summary>
        internal static string AddressSizeOptions_3Bytes {
            get {
                return ResourceManager.GetString("AddressSizeOptions_3Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Bytes.
        /// </summary>
        internal static string AddressSizeOptions_4Bytes {
            get {
                return ResourceManager.GetString("AddressSizeOptions_4Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PointerScan.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string AutoButton_Label {
            get {
                return ResourceManager.GetString("AutoButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Depth:.
        /// </summary>
        internal static string MaxDepthLabel_Label {
            get {
                return ResourceManager.GetString("MaxDepthLabel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Offset (Hex):.
        /// </summary>
        internal static string MaxOffsetLabel_Label {
            get {
                return ResourceManager.GetString("MaxOffsetLabel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Base offset (Hex):.
        /// </summary>
        internal static string RamOffsetLabel_Label {
            get {
                return ResourceManager.GetString("RamOffsetLabel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string ResetButton_Label {
            get {
                return ResourceManager.GetString("ResetButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target address!.
        /// </summary>
        internal static string ResultsLabel_ErrorAddress {
            get {
                return ResourceManager.GetString("ResultsLabel_ErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid pointer size!.
        /// </summary>
        internal static string ResultsLabel_ErrorAddressSize {
            get {
                return ResourceManager.GetString("ResultsLabel_ErrorAddressSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid maximum pointer offset!.
        /// </summary>
        internal static string ResultsLabel_ErrorMaxOffset {
            get {
                return ResourceManager.GetString("ResultsLabel_ErrorMaxOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RAM offset!.
        /// </summary>
        internal static string ResultsLabel_ErrorRAMOffset {
            get {
                return ResourceManager.GetString("ResultsLabel_ErrorRAMOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} Result(s)!.
        /// </summary>
        internal static string ResultsLabel_Template {
            get {
                return ResourceManager.GetString("ResultsLabel_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescan.
        /// </summary>
        internal static string StartButton_Rescan {
            get {
                return ResourceManager.GetString("StartButton_Rescan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartButton_Start {
            get {
                return ResourceManager.GetString("StartButton_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ROM loaded!.
        /// </summary>
        internal static string StatusLabel_NoROM {
            get {
                return ResourceManager.GetString("StatusLabel_NoROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Size:.
        /// </summary>
        internal static string ValueSizeLabel_Label {
            get {
                return ResourceManager.GetString("ValueSizeLabel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Byte.
        /// </summary>
        internal static string ValueSizeOptions_1Byte {
            get {
                return ResourceManager.GetString("ValueSizeOptions_1Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Bytes.
        /// </summary>
        internal static string ValueSizeOptions_2Bytes {
            get {
                return ResourceManager.GetString("ValueSizeOptions_2Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Bytes.
        /// </summary>
        internal static string ValueSizeOptions_3Bytes {
            get {
                return ResourceManager.GetString("ValueSizeOptions_3Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Bytes.
        /// </summary>
        internal static string ValueSizeOptions_4Bytes {
            get {
                return ResourceManager.GetString("ValueSizeOptions_4Bytes", resourceCulture);
            }
        }
    }
}
